# -*- coding: utf-8 -*-
"""GCD Idea.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15sRvdaQ6GEW4j8ChxD9lpH3nnA_ljyqh
"""

def GCD(x, y):
    while(y):
        x, y = y, x % y
    return x

def check(x):
    for i in range(2,x):
        if (x%i ==0):
            return False
    return(True)

import random
def generate():
    seed = random.randint(100,1000)
    prime = []
    for i in range(10,seed):
        if(check(i)):
            prime.append(i)
    return(random.choice(prime))

def genotps(mu):
    otps = []
    i = 1
    while(i<=mu):
        sec = generate()
        if(sec not in otps):
            otps.append(sec)
            i+=1
    return(otps)

import math
def checkotp(minus,seed,localotps):
    #print(localotps)
    otpsum = 0
    ref = GCD(\
              localotps[random.randint(0,math.floor(len(localotps)/2))],\
              localotps[random.randint(math.floor(len(localotps)/2),len(localotps)-1)])
    print("Ref",ref)#BH
    if(len(set(localotps)) == len(localotps)):
        for i in range(0,len(localotps)-1):
            if(GCD(localotps[i],localotps[i+1]) == ref):
                k=GCD(localotps[i],localotps[i+1])
                print(k)
                otpsum = otpsum + GCD(localotps[i],localotps[i+1])
            else:
                return(False)
        if(otpsum >= (seed*(minus-1))):
            return(True)
        else:
            return(False)
    else:
        return(False)
        
    '''
    for i in range(0,len(localotps)-1):
        #print("Hello")#BH
        if(GCD(localotps[i],localotps[i+1]) == ref):
            k=GCD(localotps[i],localotps[i+1])
            print(k)
            otpsum = otpsum + GCD(localotps[i],localotps[i+1])
            #print(otpsum)
        else:
            return(False)
    #print("otpsum",otpsum)#BH
    if(otpsum >= (seed*(minus-1))):
        return(True)
    else:
        return(False)
    '''
#checkotp(10,seed,allotps)

#checkotp(4,seed,[11035, 2355,435,11085,105])

#allotp #[2,3,5,7]

#seed #15

#allotps #[30,45,75,105]



